Documentation
CampusAI/Hamiltonian-Generative-Networks pull request #62
Opened 2020-10-26 10:07 UTC by stathius

Some documentation/comments/docstrings that were missing.

2020-10-26 10:51 UTC, OleguerCanal requested changes

2020-10-26 10:51 UTC, OleguerCanal commented on utilities/losses.py
> +        (Tensor): the constraing value as MSE minus the tolerance
```suggestion
    Args:
        target (toch.Tensor): the rollout target.
        prediction (torch.Tensor): the prediction of the model.
        tol (float): the tolerance we accept between target and prediction.

    Returns:
        (tuple(torch.Tensor, torch.Tensor)): the constraing value as MSE minus the tolerance, and MSE.
```

2020-11-12 11:45 UTC, fedetask approved these changes
Great! I think we can merge this

2020-11-14 16:12 UTC, OleguerCanal approved these changes

2020-11-14 16:12 UTC, merged